### ISSUE TITLE
Run pylint on all python files and lint them

### ISSUE THREAD

**Issue by BaronJake** [BaronJake/translate_files#5]
Linting ensures that all files follow best coding practices and have similar styles. It's usually something that gets ignored when writing one-off code, but it makes the code more maintainable when it's something that will be used repeatedly.

https://dbader.org/blog/python-code-linting

https://www.youtube.com/watch?v=fFY5103p5-c

There are several python packages that accomplish this.

`black` will automatically reformat files and is a super useful first step in linting. Run it by installing black and executing on the commandline:

`black . ` to run on all files int he current directory and sub directories.

`pylint` is another package for linting python files according to PEP8 style guide. Instead of reformatting for you like black does, it just tells you what line should change and what it recommends changing. There's lots of options with pylint so you can specify lots of different rules to ignore or values for maximum line length. Run it by installing pylint and execute:

pylint --rcfile .pylintrc .

instead of `pylint` you can use `flake8`, but I'm not as familiar with that one. For sure run `black` and then either `pylint` or `flake8`.

**Comment by gunjan-l** [comment]
Hey @BaronJake  ,
I'm interested in contributing to this issue, so before I start working
it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by BaronJake** [comment]
@9gl Yeah this should be pretty simple. There are a few resources in the issue description on what linting is and why it's a good idea to have well linted code. Basically I want all python files in this repo to be linted using `black`, followed by `pylint`. You can use pip to install both, and commands for running them on the command line are in the issue description as well. `black` will do everything it's going to do when you run it. `pylint` will just tell you what it recommends changing, and successfully  completing this issue will require you to address all of `pylint`'s recommendations and getting a score of `10.0` on the pylint report. I hope this helps. Let me know if you have any questions.
